# Used when a commit is pushed to the repository
# This makes use of caching for faster builds and uploads the resulting artifacts
name: build-commit

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract current branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "branch=${ref////-}" >> $GITHUB_OUTPUT
        id: ref
      - name: Checkout sources
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with: 
            cache-read-only: false
      - name: Build artifacts
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: sodium-artifacts-${{ steps.ref.outputs.branch }}
          path: |
            neoforge/build/libs/*.jar
            fabric/build/libs/*.jar
